function [tmpMarginStats, tmpMarginDecomp] = frstat_margin_step( ...
    y_grid, yvar0, est, deltaX, S, forcing)

    y_grid = y_grid(:);

    [f_ref, f_full] = clr_push_density_from_est(y_grid, yvar0, est, deltaX);

    f_ref  = max(f_ref(:),  0);
    f_full = max(f_full(:), 0);
    f_ref  = f_ref  / trapz(y_grid, f_ref);
    f_full = f_full / trapz(y_grid, f_full);

    mu_ref  = trapz(y_grid, y_grid .* f_ref);
    mu_full = trapz(y_grid, y_grid .* f_full);
    dmu_full = mu_full - mu_ref;

    loc_shift = frstat_quantile_band_shift( ...
        y_grid, f_ref, f_full, S.loc_u_band, S.loc_u_n);

    f_loc = shift_density_on_grid(y_grid, f_ref, loc_shift);
    f_loc = max(f_loc(:), 0);
    f_loc = f_loc / trapz(y_grid, f_loc);

    mstats_full = margin_decomp_stats(y_grid, f_ref, f_full, S.q_high);
    mstats_loc  = margin_decomp_stats(y_grid, f_ref, f_loc,  S.q_high);

    tmpMarginStats = struct( ...
        'forcing',    string(forcing), ...
        'q_high',     S.q_high, ...
        'r_high',     mstats_full.r_high, ...
        'median_ref', mstats_full.median_ref, ...
        'median_new', mstats_full.median_new, ...
        'd_median',   mstats_full.d_median, ...
        'iqr_ref',    mstats_full.iqr_ref, ...
        'iqr_new',    mstats_full.iqr_new, ...
        'd_iqr',      mstats_full.d_iqr, ...
        'tail_ref',   mstats_full.tail_ref, ...
        'tail_new',   mstats_full.tail_new, ...
        'd_tail',     mstats_full.d_tail, ...
        'mu_ref',     mu_ref, ...
        'mu_full',    mu_full, ...
        'dmu_full',   dmu_full);

    tmpMarginDecomp = struct( ...
        'forcing',           string(forcing), ...
        'dmu_full',          dmu_full, ...
        'loc_shift',         loc_shift, ...
        'mean_loc_gap',      dmu_full - loc_shift, ...
        'd_median_full',     mstats_full.d_median, ...
        'd_median_loconly',  mstats_loc.d_median, ...
        'd_median_dist',     mstats_full.d_median - mstats_loc.d_median, ...
        'd_iqr_full',        mstats_full.d_iqr, ...
        'd_iqr_loconly',     mstats_loc.d_iqr, ...
        'd_iqr_dist',        mstats_full.d_iqr - mstats_loc.d_iqr, ...
        'd_tail_full',       mstats_full.d_tail, ...
        'd_tail_loconly',    mstats_loc.d_tail, ...
        'd_tail_dist',       mstats_full.d_tail - mstats_loc.d_tail);
end
